---
# Check to make sure provided pvc exists, error loudly if not.  Otherwise, the management pod will just stay in pending state forever.
- name: Check provided PVC claim exists
  kubernetes.core.k8s_info:
    name: "{{ _metrics_pvc_claim }}"
    kind: PersistentVolumeClaim
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: provided_pvc
  when:
    - _metrics_pvc_claim | length

- block:
    - name: Create PVC for metrics
      kubernetes.core.k8s:
        kind: PersistentVolumeClaim
        definition: "{{ lookup('template', 'persistentvolumeclaims/metrics.yaml.j2') }}"

- block: 
    - name: Create Kubernetes CronJob for metrics
      kubernetes.core.k8s:
        name: "{{ ansible_operator_meta.name }}-metrics"
        kind: CronJob
        state: present
        definition: "{{ lookup('template', 'cronjobs/metrics.yaml.j2') }}"
        wait: true